name: Docker Push

on:
  workflow_call:
    inputs:
      run_id:
        description: 'The workflow run ID that generated the Docker artifacts'
        required: true
        type: string
      repository:
        description: 'Repository name (owner/repo)'
        required: true
        type: string

jobs:
  push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Download build metadata
        uses: actions/github-script@v7
        with:
          script: |
            // Parse repository owner/name
            const [owner, repo] = '${{ inputs.repository }}'.split('/');
            
            // Get artifacts from the specified workflow run
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: owner,
              repo: repo,
              run_id: '${{ inputs.run_id }}',
            });

            // Find build metadata artifact
            const metadataArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === 'build-metadata'
            );

            if (!metadataArtifact) {
              console.log('No build metadata found, skipping Docker push');
              return;
            }

            // Download the metadata
            const download = await github.rest.actions.downloadArtifact({
              owner: owner,
              repo: repo,
              artifact_id: metadataArtifact.id,
              archive_format: 'zip',
            });

            const fs = require('fs');
            fs.writeFileSync('metadata.zip', Buffer.from(download.data));

      - name: Extract and parse metadata
        id: metadata
        run: |
          if [ -f "metadata.zip" ]; then
            unzip metadata.zip
            if [ -f "build-metadata.json" ]; then
              # Parse JSON and set outputs
              echo "repository=$(jq -r '.repository' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "sha=$(jq -r '.sha' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "short-sha=$(jq -r '.short_sha' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "epoch=$(jq -r '.epoch' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "ref=$(jq -r '.ref' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "event-name=$(jq -r '.event_name' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "pr-number=$(jq -r '.pr_number' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "build-pr-image=$(jq -r '.build_pr_image' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "is-main-push=$(jq -r '.is_main_push' build-metadata.json)" >> $GITHUB_OUTPUT
              echo "has-metadata=true" >> $GITHUB_OUTPUT
              
              # Display metadata for debugging
              echo "Build metadata:"
              cat build-metadata.json | jq .
            else
              echo "has-metadata=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "has-metadata=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.metadata.outputs.has-metadata == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to the remote registry
        if: steps.metadata.outputs.has-metadata == 'true'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download and push test image
        if: steps.metadata.outputs.has-metadata == 'true' && steps.metadata.outputs.build-pr-image == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Parse repository owner/name
            const [owner, repo] = '${{ inputs.repository }}'.split('/');
            
            // Download test image artifact
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: owner,
              repo: repo,
              run_id: '${{ inputs.run_id }}',
            });

            const testImageArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === 'test-docker-image'
            );

            if (testImageArtifact) {
              const download = await github.rest.actions.downloadArtifact({
                owner: owner,
                repo: repo,
                artifact_id: testImageArtifact.id,
                archive_format: 'zip',
              });

              const fs = require('fs');
              fs.writeFileSync('test-image.zip', Buffer.from(download.data));
            }

      - name: Load and push test image
        if: steps.metadata.outputs.has-metadata == 'true' && steps.metadata.outputs.build-pr-image == 'true'
        run: |
          if [ -f "test-image.zip" ]; then
            unzip test-image.zip
            if [ -f "test-image.tar.gz" ]; then
              # Load the image
              docker load < test-image.tar.gz
              
              # Determine the tag based on event type
              if [ "${{ steps.metadata.outputs.event-name }}" = "pull_request" ]; then
                TAG="quay.io/${{ steps.metadata.outputs.repository }}:pr-${{ steps.metadata.outputs.pr-number }}-${{ steps.metadata.outputs.short-sha }}"
              else
                TAG="quay.io/${{ steps.metadata.outputs.repository }}:test-${{ steps.metadata.outputs.short-sha }}"
              fi
              
              # Re-tag and push
              docker tag ${{ steps.metadata.outputs.sha }} "$TAG"
              docker push "$TAG"
              echo "Pushed test image: $TAG"
            fi
          fi

      - name: Download and push production image
        if: steps.metadata.outputs.has-metadata == 'true' && steps.metadata.outputs.is-main-push == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Parse repository owner/name
            const [owner, repo] = '${{ inputs.repository }}'.split('/');
            
            // Download production image artifact
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: owner,
              repo: repo,
              run_id: '${{ inputs.run_id }}',
            });

            const prodImageArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === 'prod-docker-image'
            );

            if (prodImageArtifact) {
              const download = await github.rest.actions.downloadArtifact({
                owner: owner,
                repo: repo,
                artifact_id: prodImageArtifact.id,
                archive_format: 'zip',
              });

              const fs = require('fs');
              fs.writeFileSync('prod-image.zip', Buffer.from(download.data));
            }

      - name: Load and push production image
        if: steps.metadata.outputs.has-metadata == 'true' && steps.metadata.outputs.is-main-push == 'true'
        run: |
          if [ -f "prod-image.zip" ]; then
            unzip prod-image.zip
            if [ -f "prod-image.tar" ]; then
              # Load the image
              docker load < prod-image.tar
              
              # Tag and push production image
              TAG="quay.io/${{ steps.metadata.outputs.repository }}:${{ steps.metadata.outputs.epoch }}-${{ steps.metadata.outputs.short-sha }}"
              docker tag temp-prod-image "$TAG"
              docker push "$TAG"
              echo "Pushed production image: $TAG"
            fi
          fi 